version: '3'
services:
  filtered:
    build:
      context: .
    working_dir: /home/pwn
    container_name: filtered
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9001:9999"
    entrypoint: /etc/init.sh
    restart: always
